### ISSUE TITLE
고장난 키보드

### ISSUE THREAD

**Issue by airhood** [noob1301/Airhood_is_idiot#4]
어떤 사람이 키보드 키캡을 잘못 바꿔 껴서 키가 잘못 입력되었다.

**(원래 키보드 입력) <-> (바꿔있던 키)**
**a <-> f
c <-> j
k <-> u
p <-> q**

**원래 입력하려고 했던 문장**을 출력하세요.

**Comment by noob1301** [comment]
그럼 z는 어디로 감?

**Comment by noob1301** [comment]
아 안말해 줘도 됨

**Comment by airhood** [comment]
만약 입력이 q로 되어있으면, 그 사람은 p를 입력하려고 했던 거임.
만약 입력이 p로 되어있으면, 그 사람은 q를 입력하려고 했던 거고.

두 개의 키가 서로 바뀌는 거임

**Comment by noob1301** [comment]
p가 1?

**Comment by airhood** [comment]
q임. 수정함
