### ISSUE TITLE
근의 공식

### ISSUE THREAD

**Issue by airhood** [noob1301/Airhood_is_idiot#5]
**ax + by + c = 0
px + qy + r= 0**

위 두 식을 연립한 **연립방정식의 두 해**를 구하세요.

**[입력형식]**
a, b, c, p, q, r 을 따로 입력받는다.
a, b, c, p, q, r 은 **정수**.
a, b, c, p, q, r 은 **0이 될 수 있다**.

**[특수조건]**
식이 모순일 경우, **해가 없다고 표시**한다.

**[출력형식]**
ex) x = 1, 1/5
x는 소수가 아닌 **분수**이어야 하고, **약분**이 되어 있어야 한다.

**Comment by noob1301** [comment]
x 하나뿐인데 연립할 필요가 있나?

**Comment by airhood** [comment]
나 뭐하냐 ㅋㅋㅋㅋ. 수정할게
